export const API = {
    BASE_URL: process.env.API_BASE_URL || 'http://localhost:8080/api',
    TIMEOUT: 30000,
    RETRY_ATTEMPTS: 3,
    RETRY_DELAY: 1000,
} as const;

export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/auth/login',
        REGISTER: '/auth/register',
        LOGOUT: '/auth/logout',
        REFRESH_TOKEN: '/auth/refresh-token',
        FORGOT_PASSWORD: '/auth/forgot-password',
        RESET_PASSWORD: '/auth/reset-password',
        CHANGE_PASSWORD: '/auth/change-password',
        VERIFY_EMAIL: '/auth/verify-email',
    },
    USERS: {
        BASE: '/users',
        GET_ALL: '/users',
        GET_BY_ID: (id: number) => `/users/${id}`,
        CREATE: '/users',
        UPDATE: (id: number) => `/users/${id}`,
        DELETE: (id: number) => `/users/${id}`,
        ACTIVATE: (id: number) => `/users/${id}/activate`,
        DEACTIVATE: (id: number) => `/users/${id}/deactivate`,
        ROLES: '/users/roles',
        ASSIGN_ROLES: (id: number) => `/users/${id}/roles`,
        PROFILE: '/users/profile',
        STATS: '/users/stats',
    },
    ROLES: {
        BASE: '/roles',
        GET_ALL: '/roles',
        GET_BY_ID: (id: number) => `/roles/${id}`,
        CREATE: '/roles',
        UPDATE: (id: number) => `/roles/${id}`,
        DELETE: (id: number) => `/roles/${id}`,
        PERMISSIONS: '/roles/permissions',
        PERMISSIONS_GROUPED: '/roles/permissions/grouped',
        ASSIGN_PERMISSION: (roleId: number, permissionId: number) =>
            `/roles/${roleId}/permissions/${permissionId}`,
        USERS_IN_ROLE: (roleId: number) => `/roles/${roleId}/users`,
        STATS: '/roles/stats',
    },
    PRODUCTS: {
        BASE: '/products',
        GET_ALL: '/products',
        GET_BY_ID: (id: number) => `/products/${id}`,
        GET_BY_SKU: (sku: string) => `/products/sku/${sku}`,
        SEARCH: '/products/search',
        CREATE: '/products',
        UPDATE: (id: number) => `/products/${id}`,
        DELETE: (id: number) => `/products/${id}`,
        ACTIVATE: (id: number) => `/products/${id}/activate`,
        DEACTIVATE: (id: number) => `/products/${id}/deactivate`,
        BY_CATEGORY: (categoryId: number) => `/products/category/${categoryId}`,
        BY_BRAND: (brandId: number) => `/products/brand/${brandId}`,
        LOW_STOCK: '/products/needing-reorder',
        CHECK_SKU: (sku: string) => `/products/check-sku?sku=${sku}`,
        CHECK_BARCODE: (barcode: string) => `/products/check-barcode?barcode=${barcode}`,
    },
    CATEGORIES: {
        BASE: '/categories',
        GET_ALL: '/categories',
        GET_BY_ID: (id: number) => `/categories/${id}`,
        CREATE: '/categories',
        UPDATE: (id: number) => `/categories/${id}`,
        DELETE: (id: number) => `/categories/${id}`,
        ROOT: '/categories/root',
        SUBCATEGORIES: (parentId: number) => `/categories/${parentId}/subcategories`,
    },
    BRANDS: {
        BASE: '/brands',
        GET_ALL: '/brands',
        GET_BY_ID: (id: number) => `/brands/${id}`,
        CREATE: '/brands',
        UPDATE: (id: number) => `/brands/${id}`,
        DELETE: (id: number) => `/brands/${id}`,
    },
    INVENTORY: {
        BASE: '/inventory',
        GET_ALL: '/inventory',
        GET_BY_ID: (id: number) => `/inventory/${id}`,
        GET_BY_PRODUCT: (productId: number) => `/inventory/product/${productId}`,
        GET_BY_WAREHOUSE: (warehouseId: number) => `/inventory/warehouse/${warehouseId}`,
        CREATE: '/inventory',
        UPDATE: (id: number) => `/inventory/${id}`,
        DELETE: (id: number) => `/inventory/${id}`,
        ADJUST: '/inventory/adjust',
        TRANSFER: '/inventory/transfer',
        CHECK_AVAILABILITY: '/inventory/check-availability',
        ALERTS: {
            LOW_STOCK: '/inventory/alerts/low-stock',
            OUT_OF_STOCK: '/inventory/alerts/out-of-stock',
        },
        STATS: {
            LOW_STOCK_COUNT: '/inventory/stats/low-stock-count',
            OUT_OF_STOCK_COUNT: '/inventory/stats/out-of-stock-count',
        },
    },
    WAREHOUSES: {
        BASE: '/warehouses',
        GET_ALL: '/warehouses',
        GET_BY_ID: (id: number) => `/warehouses/${id}`,
        GET_BY_CODE: (code: string) => `/warehouses/code/${code}`,
        CREATE: '/warehouses',
        UPDATE: (id: number) => `/warehouses/${id}`,
        DELETE: (id: number) => `/warehouses/${id}`,
        ACTIVATE: (id: number) => `/warehouses/${id}/activate`,
        DEACTIVATE: (id: number) => `/warehouses/${id}/deactivate`,
        PRIMARY: '/warehouses/primary',
        ACTIVE: '/warehouses/active',
    },
    STOCK_MOVEMENTS: {
        BASE: '/stock-movements',
        GET_ALL: '/stock-movements',
        GET_BY_ID: (id: number) => `/stock-movements/${id}`,
        GET_BY_REFERENCE: (ref: string) => `/stock-movements/reference/${ref}`,
        GET_BY_PRODUCT: (productId: number) => `/stock-movements/product/${productId}`,
        GET_BY_WAREHOUSE: (warehouseId: number) => `/stock-movements/warehouse/${warehouseId}`,
        GET_BY_DATE_RANGE: '/stock-movements/date-range',
        CREATE: '/stock-movements',
    },
    CUSTOMERS: {
        BASE: '/customers',
        GET_ALL: '/customers',
        GET_BY_ID: (id: number) => `/customers/${id}`,
        GET_BY_CODE: (code: string) => `/customers/code/${code}`,
        GET_BY_EMAIL: (email: string) => `/customers/email/${email}`,
        GET_BY_PHONE: (phone: string) => `/customers/phone/${phone}`,
        SEARCH: '/customers/search',
        CREATE: '/customers',
        UPDATE: (id: number) => `/customers/${id}`,
        DELETE: (id: number) => `/customers/${id}`,
        ACTIVATE: (id: number) => `/customers/${id}/activate`,
        DEACTIVATE: (id: number) => `/customers/${id}/deactivate`,
        BLOCK: (id: number) => `/customers/${id}/block`,
        BY_STATUS: (status: string) => `/customers/status/${status}`,
        WITH_DUE: '/customers/with-due',
        TOP: '/customers/top',
        SUMMARIES: '/customers/summaries',
        STATS: {
            COUNT: '/customers/stats/count',
            NEW_TODAY: '/customers/stats/new-today',
        },
        CHECK: {
            EMAIL: (email: string) => `/customers/check-email?email=${email}`,
            PHONE: (phone: string) => `/customers/check-phone?phone=${phone}`,
        },
    },
    CUSTOMER_DUES: {
        BASE: '/customer-dues',
        GET_BY_ID: (id: number) => `/customer-dues/${id}`,
        GET_BY_REFERENCE: (ref: string) => `/customer-dues/reference/${ref}`,
        GET_BY_CUSTOMER: (customerId: number) => `/customer-dues/customer/${customerId}`,
        CREATE: '/customer-dues',
        OVERDUE: '/customer-dues/overdue',
        DATE_RANGE: '/customer-dues/date-range',
        PAYMENT: (id: number) => `/customer-dues/${id}/payment`,
        STATUS: (id: number) => `/customer-dues/${id}/status`,
        SEND_REMINDER: (id: number) => `/customer-dues/${id}/send-reminder`,
        NEEDING_REMINDER: '/customer-dues/needing-reminder',
        STATS: {
            TOTAL_DUE: '/customer-dues/stats/total-due',
            TOTAL_OVERDUE: '/customer-dues/stats/total-overdue',
            OVERDUE_COUNT: '/customer-dues/stats/overdue-count',
        },
    },
    LOYALTY: {
        SUMMARY: (customerId: number) => `/loyalty/customer/${customerId}/summary`,
        POINTS: (customerId: number) => `/loyalty/customer/${customerId}/points`,
        TIER: (customerId: number) => `/loyalty/customer/${customerId}/tier`,
        TRANSACTIONS: (customerId: number) => `/loyalty/customer/${customerId}/transactions`,
        RECENT_TRANSACTIONS: (customerId: number, limit: number) =>
            `/loyalty/customer/${customerId}/recent-transactions?limit=${limit}`,
        EARN: (customerId: number) => `/loyalty/customer/${customerId}/earn`,
        REDEEM: (customerId: number) => `/loyalty/customer/${customerId}/redeem`,
        ADJUST: (customerId: number) => `/loyalty/customer/${customerId}/adjust`,
        POINTS_TO_NEXT_TIER: (customerId: number) => `/loyalty/customer/${customerId}/points-to-next-tier`,
        NEXT_TIER: (customerId: number) => `/loyalty/customer/${customerId}/next-tier`,
        POINTS_VALUE: (customerId: number, points: number) =>
            `/loyalty/customer/${customerId}/points-value?points=${points}`,
        CAN_REDEEM: (customerId: number, points: number) =>
            `/loyalty/customer/${customerId}/can-redeem?points=${points}`,
    },
    SALES: {
        BASE: '/sales',
        GET_ALL: '/sales',
        GET_BY_ID: (id: number) => `/sales/${id}`,
        GET_BY_INVOICE: (invoice: string) => `/sales/invoice/${invoice}`,
        GET_BY_CUSTOMER: (customerId: number) => `/sales/customer/${customerId}`,
        GET_BY_DATE_RANGE: '/sales/date-range',
        GET_BY_STATUS: (status: string) => `/sales/status/${status}`,
        CREATE: '/sales',
        UPDATE: (id: number) => `/sales/${id}`,
        CANCEL: (id: number) => `/sales/${id}/cancel`,
        RETURN: (id: number) => `/sales/${id}/return`,
        RECENT: '/sales/recent',
        STATS: {
            TOTAL: '/sales/stats/total',
            COUNT: '/sales/stats/count',
        },
        CHECK_INVOICE: (invoice: string) => `/sales/check-invoice?invoiceNumber=${invoice}`,
    },
    PAYMENTS: {
        BASE: '/payments',
        GET_ALL: '/payments',
        GET_BY_ID: (id: number) => `/payments/${id}`,
        GET_BY_REFERENCE: (ref: string) => `/payments/reference/${ref}`,
        GET_BY_SALE: (saleId: number) => `/payments/sale/${saleId}`,
        GET_BY_DATE_RANGE: '/payments/date-range',
        CREATE: '/payments',
        CANCEL: (id: number) => `/payments/${id}/cancel`,
        STATS: {
            TOTAL: '/payments/stats/total',
        },
        CHECK_TRANSACTION: (txnId: string) => `/payments/check-transaction?transactionId=${txnId}`,
    },
    INVOICES: {
        BASE: '/invoices',
        GENERATE: (saleId: number) => `/invoices/generate/${saleId}`,
        GET_BY_ID: (id: number) => `/invoices/${id}`,
        GET_BY_NUMBER: (number: string) => `/invoices/number/${number}`,
        GET_BY_SALE: (saleId: number) => `/invoices/sale/${saleId}`,
        GET_ALL: '/invoices',
        GET_BY_DATE_RANGE: '/invoices/date-range',
        PDF: (id: number) => `/invoices/${id}/pdf`,
        EMAIL: (id: number) => `/invoices/${id}/email`,
        MARK_PRINTED: (id: number) => `/invoices/${id}/mark-printed`,
        MARK_EMAILED: (id: number) => `/invoices/${id}/mark-emailed`,
    },
    SUPPLIERS: {
        BASE: '/suppliers',
        GET_ALL: '/suppliers',
        GET_BY_ID: (id: number) => `/suppliers/${id}`,
        GET_BY_CODE: (code: string) => `/suppliers/code/${code}`,
        GET_BY_EMAIL: (email: string) => `/suppliers/email/${email}`,
        GET_BY_PHONE: (phone: string) => `/suppliers/phone/${phone}`,
        SEARCH: '/suppliers/search',
        CREATE: '/suppliers',
        UPDATE: (id: number) => `/suppliers/${id}`,
        DELETE: (id: number) => `/suppliers/${id}`,
        ACTIVATE: (id: number) => `/suppliers/${id}/activate`,
        DEACTIVATE: (id: number) => `/suppliers/${id}/deactivate`,
        BLACKLIST: (id: number) => `/suppliers/${id}/blacklist`,
        BY_STATUS: (status: string) => `/suppliers/status/${status}`,
        WITH_OUTSTANDING: '/suppliers/with-outstanding',
        SUMMARIES: '/suppliers/summaries',
        RATINGS: {
            ADD: (id: number) => `/suppliers/${id}/ratings`,
            AVERAGE: (id: number) => `/suppliers/${id}/average-rating`,
        },
        CHECK: {
            EMAIL: (email: string) => `/suppliers/check-email?email=${email}`,
            PHONE: (phone: string) => `/suppliers/check-phone?phone=${phone}`,
        },
    },
    PURCHASES: {
        BASE: '/purchases',
        GET_ALL: '/purchases',
        GET_BY_ID: (id: number) => `/purchases/${id}`,
        GET_BY_ORDER_NUMBER: (number: string) => `/purchases/order-number/${number}`,
        GET_BY_SUPPLIER: (supplierId: number) => `/purchases/supplier/${supplierId}`,
        GET_BY_STATUS: (status: string) => `/purchases/status/${status}`,
        GET_BY_DATE_RANGE: '/purchases/date-range',
        CREATE: '/purchases',
        UPDATE: (id: number) => `/purchases/${id}`,
        APPROVE: (id: number) => `/purchases/${id}/approve`,
        CANCEL: (id: number) => `/purchases/${id}/cancel`,
        RECEIVE: '/purchase-receipts',
        PAYMENT: (id: number) => `/purchases/${id}/payment`,
        RECENT: '/purchases/recent',
        STATS: {
            TOTAL: '/purchases/stats/total',
            PENDING_APPROVAL: '/purchases/stats/pending-approval',
        },
        CHECK_ORDER_NUMBER: (number: string) => `/purchases/check-order-number?orderNumber=${number}`,
    },
    SUPPLIER_PAYMENTS: {
        BASE: '/supplier-payments',
        GET_ALL: '/supplier-payments',
        GET_BY_ID: (id: number) => `/supplier-payments/${id}`,
        GET_BY_REFERENCE: (ref: string) => `/supplier-payments/reference/${ref}`,
        GET_BY_SUPPLIER: (supplierId: number) => `/supplier-payments/supplier/${supplierId}`,
        GET_BY_PURCHASE: (purchaseId: number) => `/supplier-payments/purchase/${purchaseId}`,
        GET_BY_DATE_RANGE: '/supplier-payments/date-range',
        CREATE: '/supplier-payments',
        CANCEL: (id: number) => `/supplier-payments/${id}/cancel`,
        STATS: {
            TOTAL: '/supplier-payments/stats/total',
        },
    },
    DISTRIBUTORS: {
        BASE: '/distributors',
        GET_ALL: '/distributors',
        GET_BY_ID: (id: number) => `/distributors/${id}`,
        GET_BY_CODE: (code: string) => `/distributors/code/${code}`,
        GET_BY_EMAIL: (email: string) => `/distributors/email/${email}`,
        GET_BY_PHONE: (phone: string) => `/distributors/phone/${phone}`,
        SEARCH: '/distributors/search',
        CREATE: '/distributors',
        UPDATE: (id: number) => `/distributors/${id}`,
        DELETE: (id: number) => `/distributors/${id}`,
        ACTIVATE: (id: number) => `/distributors/${id}/activate`,
        DEACTIVATE: (id: number) => `/distributors/${id}/deactivate`,
        BLACKLIST: (id: number) => `/distributors/${id}/blacklist`,
        BY_REGION: (region: string) => `/distributors/region/${region}`,
        BY_TERRITORY: (territory: string) => `/distributors/territory/${territory}`,
        WITH_OUTSTANDING: '/distributors/with-outstanding',
        SUMMARIES: '/distributors/summaries',
        CHECK: {
            EMAIL: (email: string) => `/distributors/check-email?email=${email}`,
            PHONE: (phone: string) => `/distributors/check-phone?phone=${phone}`,
        },
    },
    DISTRIBUTOR_ORDERS: {
        BASE: '/distributor-orders',
        GET_ALL: '/distributor-orders',
        GET_BY_ID: (id: number) => `/distributor-orders/${id}`,
        GET_BY_NUMBER: (number: string) => `/distributor-orders/number/${number}`,
        GET_BY_DISTRIBUTOR: (distributorId: number) => `/distributor-orders/distributor/${distributorId}`,
        GET_BY_STATUS: (status: string) => `/distributor-orders/status/${status}`,
        GET_BY_DATE_RANGE: '/distributor-orders/date-range',
        CREATE: '/distributor-orders',
        UPDATE: (id: number) => `/distributor-orders/${id}`,
        APPROVE: (id: number) => `/distributor-orders/${id}/approve`,
        PROCESS: (id: number) => `/distributor-orders/${id}/process`,
        SHIP: (id: number) => `/distributor-orders/${id}/ship`,
        DELIVER: (id: number) => `/distributor-orders/${id}/deliver`,
        CANCEL: (id: number) => `/distributor-orders/${id}/cancel`,
        RECENT: '/distributor-orders/recent',
        DELAYED: '/distributor-orders/delayed',
        STATS: {
            TOTAL: '/distributor-orders/stats/total',
            PENDING: '/distributor-orders/stats/pending',
        },
        CHECK_ORDER_NUMBER: (number: string) => `/distributor-orders/check-order-number?orderNumber=${number}`,
    },
    DISTRIBUTOR_PAYMENTS: {
        BASE: '/distributor-payments',
        GET_ALL: '/distributor-payments',
        GET_BY_ID: (id: number) => `/distributor-payments/${id}`,
        GET_BY_REFERENCE: (ref: string) => `/distributor-payments/reference/${ref}`,
        GET_BY_DISTRIBUTOR: (distributorId: number) => `/distributor-payments/distributor/${distributorId}`,
        GET_BY_ORDER: (orderId: number) => `/distributor-payments/order/${orderId}`,
        GET_BY_DATE_RANGE: '/distributor-payments/date-range',
        CREATE: '/distributor-payments',
        CANCEL: (id: number) => `/distributor-payments/${id}/cancel`,
        STATS: {
            TOTAL: '/distributor-payments/stats/total',
            BY_DISTRIBUTOR: (distributorId: number) => `/distributor-payments/stats/distributor/${distributorId}/total`,
        },
    },
    EXPENSES: {
        BASE: '/expenses',
        GET_ALL: '/expenses',
        GET_BY_ID: (id: number) => `/expenses/${id}`,
        GET_BY_NUMBER: (number: string) => `/expenses/number/${number}`,
        GET_BY_CATEGORY: (categoryId: number) => `/expenses/category/${categoryId}`,
        GET_BY_USER: (userId: number) => `/expenses/user/${userId}`,
        GET_BY_STATUS: (status: string) => `/expenses/status/${status}`,
        GET_BY_DATE_RANGE: '/expenses/date-range',
        GET_BY_VENDOR: '/expenses/vendor',
        CREATE: '/expenses',
        UPDATE: (id: number) => `/expenses/${id}`,
        APPROVE: (id: number) => `/expenses/${id}/approve`,
        REJECT: (id: number) => `/expenses/${id}/reject`,
        MARK_PAID: (id: number) => `/expenses/${id}/mark-paid`,
        CANCEL: (id: number) => `/expenses/${id}/cancel`,
        UPLOAD_RECEIPT: (id: number) => `/expenses/${id}/upload-receipt`,
        RECENT: '/expenses/recent',
        SUMMARY: '/expenses/summary',
        STATS: {
            TOTAL: '/expenses/stats/total',
            PENDING_APPROVAL: '/expenses/stats/pending-approval',
        },
        CHECK_EXPENSE_NUMBER: (number: string) => `/expenses/check-expense-number?expenseNumber=${number}`,
    },
    EXPENSE_CATEGORIES: {
        BASE: '/expense-categories',
        GET_ALL: '/expense-categories',
        GET_BY_ID: (id: number) => `/expense-categories/${id}`,
        GET_BY_CODE: (code: string) => `/expense-categories/code/${code}`,
        GET_BY_NAME: (name: string) => `/expense-categories/name/${name}`,
        CREATE: '/expense-categories',
        UPDATE: (id: number) => `/expense-categories/${id}`,
        DELETE: (id: number) => `/expense-categories/${id}`,
        ACTIVATE: (id: number) => `/expense-categories/${id}/activate`,
        DEACTIVATE: (id: number) => `/expense-categories/${id}/deactivate`,
        ROOT: '/expense-categories/root',
        SUBCATEGORIES: (parentId: number) => `/expense-categories/${parentId}/subcategories`,
        BY_TYPE: (type: string) => `/expense-categories/type/${type}`,
        SEARCH: '/expense-categories/search',
        BUDGET: (id: number) => `/expense-categories/${id}/budget`,
        TOTAL_EXPENSES: (id: number, period: string) =>
            `/expense-categories/${id}/total-expenses?period=${period}`,
        CHECK: {
            NAME: (name: string) => `/expense-categories/check-name?name=${name}`,
            CODE: (code: string) => `/expense-categories/check-code?categoryCode=${code}`,
        },
    },
    RECURRING_EXPENSES: {
        BASE: '/recurring-expenses',
        GET_ALL: '/recurring-expenses',
        GET_BY_ID: (id: number) => `/recurring-expenses/${id}`,
        GET_BY_NUMBER: (number: string) => `/recurring-expenses/number/${number}`,
        GET_BY_CATEGORY: (categoryId: number) => `/recurring-expenses/category/${categoryId}`,
        GET_BY_FREQUENCY: (frequency: string) => `/recurring-expenses/frequency/${frequency}`,
        CREATE: '/recurring-expenses',
        UPDATE: (id: number) => `/recurring-expenses/${id}`,
        DELETE: (id: number) => `/recurring-expenses/${id}`,
        ACTIVATE: (id: number) => `/recurring-expenses/${id}/activate`,
        DEACTIVATE: (id: number) => `/recurring-expenses/${id}/deactivate`,
        GENERATE: (id: number) => `/recurring-expenses/${id}/generate`,
        DUE_FOR_GENERATION: '/recurring-expenses/due-for-generation',
        CHECK_NUMBER: (number: string) => `/recurring-expenses/check-number?recurringExpenseNumber=${number}`,
    },
    REPORTS: {
        GENERATE: '/reports/generate',
        DOWNLOAD: '/reports/download',
        FORMATS: (type: string) => `/reports/formats/${type}`,
        GET_ALL: '/reports',
        GET_BY_ID: (id: number) => `/reports/${id}`,
        GET_BY_REPORT_ID: (reportId: string) => `/reports/report-id/${reportId}`,
        GET_BY_TYPE: (type: string) => `/reports/type/${type}`,
        GET_BY_USER: (userId: number) => `/reports/user/${userId}`,
        GET_BY_DATE_RANGE: '/reports/date-range',
        DELETE: (id: number) => `/reports/${id}`,
        DOWNLOAD_FILE: (id: number) => `/reports/${id}/download`,
        DASHBOARD_SUMMARY: '/reports/dashboard/summary',
        SALES: '/reports/sales',
        INVENTORY: '/reports/inventory',
        PURCHASE: '/reports/purchase',
        FINANCIAL: '/reports/financial',
        CUSTOMER: '/reports/customer',
        EXPENSE: '/reports/expense',
        TAX: '/reports/tax',
    },
    REPORT_SCHEDULES: {
        BASE: '/report-schedules',
        GET_ALL: '/report-schedules',
        GET_BY_ID: (id: number) => `/report-schedules/${id}`,
        GET_BY_SCHEDULE_ID: (scheduleId: string) => `/report-schedules/schedule-id/${scheduleId}`,
        CREATE: '/report-schedules',
        UPDATE: (id: number) => `/report-schedules/${id}`,
        DELETE: (id: number) => `/report-schedules/${id}`,
        ACTIVATE: (id: number) => `/report-schedules/${id}/activate`,
        DEACTIVATE: (id: number) => `/report-schedules/${id}/deactivate`,
        EXECUTE: (id: number) => `/report-schedules/${id}/execute`,
        DUE: '/report-schedules/due',
        ACTIVE: '/report-schedules/active',
        BY_USER: (userId: number) => `/report-schedules/user/${userId}`,
        CHECK_SCHEDULE_ID: (scheduleId: string) =>
            `/report-schedules/check-schedule-id?scheduleId=${scheduleId}`,
    },
    NOTIFICATIONS: {
        SEND: '/notifications/send',
        SCHEDULE: '/notifications/schedule',
        GET_BY_ID: (id: number) => `/notifications/${id}`,
        GET_BY_NOTIFICATION_ID: (notificationId: string) => `/notifications/notification-id/${notificationId}`,
        GET_BY_USER: (userId: number) => `/notifications/user/${userId}`,
        GET_BY_CUSTOMER: (customerId: number) => `/notifications/customer/${customerId}`,
        GET_UNREAD: (userId: number) => `/notifications/user/${userId}/unread`,
        UNREAD_COUNT: (userId: number) => `/notifications/user/${userId}/unread-count`,
        MARK_READ: (id: number) => `/notifications/${id}/read`,
        MARK_ALL_READ: (userId: number) => `/notifications/user/${userId}/read-all`,
        CANCEL: (id: number) => `/notifications/${id}`,
        STATS: '/notifications/stats',
        RETRY_FAILED: '/notifications/retry-failed',
    },
    NOTIFICATION_TEMPLATES: {
        BASE: '/notification-templates',
        GET_ALL: '/notification-templates',
        GET_BY_ID: (id: number) => `/notification-templates/${id}`,
        GET_BY_CODE: (code: string) => `/notification-templates/code/${code}`,
        GET_BY_TYPE: (type: string) => `/notification-templates/type/${type}`,
        GET_BY_CHANNEL: (channel: string) => `/notification-templates/channel/${channel}`,
        CREATE: '/notification-templates',
        UPDATE: (id: number) => `/notification-templates/${id}`,
        DELETE: (id: number) => `/notification-templates/${id}`,
        ACTIVATE: (id: number) => `/notification-templates/${id}/activate`,
        DEACTIVATE: (id: number) => `/notification-templates/${id}/deactivate`,
        RENDER: (code: string) => `/notification-templates/${code}/render`,
        CHECK_CODE: (code: string) => `/notification-templates/check-code?templateCode=${code}`,
    },
    DASHBOARD: {
        SUMMARY: '/dashboard/summary',
        TODAY_SALES: '/dashboard/sales/today',
        SALES_PERIOD: '/dashboard/sales/period',
        TOP_PRODUCTS: '/dashboard/products/top',
        LOW_STOCK_ALERTS: '/dashboard/inventory/low-stock',
        RECENT_ACTIVITIES: '/dashboard/activities/recent',
        DUE_SUMMARY: '/dashboard/dues/summary',
        UPCOMING_DUES: '/dashboard/dues/upcoming',
    },
    SETTINGS: {
        STORE: {
            GET: '/settings/store',
            UPDATE: '/settings/store',
            LOGO: '/settings/store/logo',
        },
        TAX: {
            GET_ALL: '/settings/taxes',
            GET_BY_ID: (id: number) => `/settings/taxes/${id}`,
            CREATE: '/settings/taxes',
            UPDATE: (id: number) => `/settings/taxes/${id}`,
            DELETE: (id: number) => `/settings/taxes/${id}`,
            SET_DEFAULT: (id: number) => `/settings/taxes/${id}/default`,
        },
        INVOICE: {
            GET: '/settings/invoice',
            UPDATE: '/settings/invoice',
        },
        PRINT: {
            GET: '/settings/print',
            UPDATE: '/settings/print',
            TEST: '/settings/print/test',
            DISCOVER: '/settings/print/discover',
        },
        BACKUP: {
            CREATE: '/settings/backup',
            RESTORE: (id: string) => `/settings/backup/${id}/restore`,
            DOWNLOAD: (id: string) => `/settings/backup/${id}/download`,
            DELETE: (id: string) => `/settings/backup/${id}`,
            GET_ALL: '/settings/backup',
            SETTINGS: '/settings/backup/settings',
        },
        SYSTEM: {
            GET: '/settings/system',
            UPDATE: '/settings/system',
            CLEAR_CACHE: '/settings/system/clear-cache',
            RESET: '/settings/system/reset',
        },
    },
} as const;