export const CURRENCIES = {
    INR: {
        code: 'INR',
        symbol: '₹',
        name: 'Indian Rupee',
        namePlural: 'Indian Rupees',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'en-IN',
    },
    USD: {
        code: 'USD',
        symbol: '$',
        name: 'US Dollar',
        namePlural: 'US Dollars',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'en-US',
    },
    EUR: {
        code: 'EUR',
        symbol: '€',
        name: 'Euro',
        namePlural: 'Euros',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: false,
        thousandsSeparator: '.',
        decimalSeparator: ',',
        format: 'de-DE',
    },
    GBP: {
        code: 'GBP',
        symbol: '£',
        name: 'British Pound',
        namePlural: 'British Pounds',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'en-GB',
    },
    JPY: {
        code: 'JPY',
        symbol: '¥',
        name: 'Japanese Yen',
        namePlural: 'Japanese Yen',
        decimalDigits: 0,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'ja-JP',
    },
    CNY: {
        code: 'CNY',
        symbol: '¥',
        name: 'Chinese Yuan',
        namePlural: 'Chinese Yuan',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'zh-CN',
    },
    AUD: {
        code: 'AUD',
        symbol: 'A$',
        name: 'Australian Dollar',
        namePlural: 'Australian Dollars',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'en-AU',
    },
    CAD: {
        code: 'CAD',
        symbol: 'C$',
        name: 'Canadian Dollar',
        namePlural: 'Canadian Dollars',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'en-CA',
    },
    SGD: {
        code: 'SGD',
        symbol: 'S$',
        name: 'Singapore Dollar',
        namePlural: 'Singapore Dollars',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'en-SG',
    },
    AED: {
        code: 'AED',
        symbol: 'د.إ',
        name: 'UAE Dirham',
        namePlural: 'UAE Dirhams',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'ar-AE',
    },
    SAR: {
        code: 'SAR',
        symbol: '﷼',
        name: 'Saudi Riyal',
        namePlural: 'Saudi Riyals',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: ',',
        decimalSeparator: '.',
        format: 'ar-SA',
    },
    CHF: {
        code: 'CHF',
        symbol: 'Fr',
        name: 'Swiss Franc',
        namePlural: 'Swiss Francs',
        decimalDigits: 2,
        rounding: 0,
        symbolBefore: true,
        thousandsSeparator: "'",
        decimalSeparator: '.',
        format: 'de-CH',
    },
} as const;

export const DEFAULT_CURRENCY = CURRENCIES.INR;

export const CURRENCY_LIST = Object.values(CURRENCIES).map(c => ({
    label: `${c.code} - ${c.name}`,
    value: c.code,
    symbol: c.symbol,
}));

export const SUPPORTED_CURRENCIES = ['INR', 'USD', 'EUR', 'GBP', 'JPY', 'CNY', 'AUD', 'CAD', 'SGD', 'AED', 'SAR', 'CHF'] as const;

export type CurrencyCode = keyof typeof CURRENCIES;
export type Currency = typeof CURRENCIES[CurrencyCode];