// User related enums
export const USER_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLOCKED: 'BLOCKED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
} as const;

// Customer related enums
export const CUSTOMER_TYPE = {
    INDIVIDUAL: 'INDIVIDUAL',
    BUSINESS: 'BUSINESS',
    WHOLESALER: 'WHOLESALER',
    RETAILER: 'RETAILER',
    DISTRIBUTOR: 'DISTRIBUTOR',
} as const;

export const CUSTOMER_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLOCKED: 'BLOCKED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
} as const;

// Due related enums
export const DUE_STATUS = {
    PENDING: 'PENDING',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    PAID: 'PAID',
    OVERDUE: 'OVERDUE',
    CANCELLED: 'CANCELLED',
    WRITTEN_OFF: 'WRITTEN_OFF',
} as const;

// Loyalty related enums
export const LOYALTY_TIER = {
    BRONZE: 'BRONZE',
    SILVER: 'SILVER',
    GOLD: 'GOLD',
    PLATINUM: 'PLATINUM',
} as const;

export const LOYALTY_TRANSACTION_TYPE = {
    EARNED: 'EARNED',
    REDEEMED: 'REDEEMED',
    EXPIRED: 'EXPIRED',
    ADJUSTED: 'ADJUSTED',
    BONUS: 'BONUS',
} as const;

// Product related enums
export const PRODUCT_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    OUT_OF_STOCK: 'OUT_OF_STOCK',
    DISCONTINUED: 'DISCONTINUED',
    COMING_SOON: 'COMING_SOON',
} as const;

export const STOCK_STATUS = {
    IN_STOCK: 'IN_STOCK',
    LOW_STOCK: 'LOW_STOCK',
    OUT_OF_STOCK: 'OUT_OF_STOCK',
    PRE_ORDER: 'PRE_ORDER',
    BACK_ORDER: 'BACK_ORDER',
    OVER_STOCK: 'OVER_STOCK',
    DAMAGED: 'DAMAGED',
    EXPIRED: 'EXPIRED',
    RESERVED: 'RESERVED',
    ON_ORDER: 'ON_ORDER',
} as const;

// Inventory related enums
export const MOVEMENT_TYPE = {
    PURCHASE_RECEIVED: 'PURCHASE_RECEIVED',
    PURCHASE_RETURN: 'PURCHASE_RETURN',
    SALES_ISSUED: 'SALES_ISSUED',
    SALES_RETURN: 'SALES_RETURN',
    TRANSFER_OUT: 'TRANSFER_OUT',
    TRANSFER_IN: 'TRANSFER_IN',
    ADJUSTMENT_ADD: 'ADJUSTMENT_ADD',
    ADJUSTMENT_REMOVE: 'ADJUSTMENT_REMOVE',
    INITIAL_STOCK: 'INITIAL_STOCK',
    DAMAGED: 'DAMAGED',
    EXPIRED: 'EXPIRED',
    COUNT_CORRECTION: 'COUNT_CORRECTION',
} as const;

// Sales related enums
export const SALE_STATUS = {
    DRAFT: 'DRAFT',
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    REFUNDED: 'REFUNDED',
    PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
    ON_HOLD: 'ON_HOLD',
} as const;

export const PAYMENT_METHOD = {
    CASH: 'CASH',
    CARD: 'CARD',
    UPI: 'UPI',
    BANK_TRANSFER: 'BANK_TRANSFER',
    CHEQUE: 'CHEQUE',
    CREDIT: 'CREDIT',
    MIXED: 'MIXED',
} as const;

export const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    PAID: 'PAID',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    OVERDUE: 'OVERDUE',
    CANCELLED: 'CANCELLED',
    REFUNDED: 'REFUNDED',
    FAILED: 'FAILED',
} as const;

// Supplier related enums
export const SUPPLIER_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLACKLISTED: 'BLACKLISTED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
    ON_HOLD: 'ON_HOLD',
} as const;

// Purchase related enums
export const PURCHASE_STATUS = {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    ORDERED: 'ORDERED',
    PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
    RECEIVED: 'RECEIVED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    ON_HOLD: 'ON_HOLD',
} as const;

// Distributor related enums
export const DISTRIBUTOR_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLACKLISTED: 'BLACKLISTED',
    PENDING_VERIFICATION: 'PENDING_VERIFICATION',
    ON_HOLD: 'ON_HOLD',
} as const;

export const DISTRIBUTOR_ORDER_STATUS = {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    PROCESSING: 'PROCESSING',
    SHIPPED: 'SHIPPED',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
    ON_HOLD: 'ON_HOLD',
} as const;

// Expense related enums
export const EXPENSE_STATUS = {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    PAID: 'PAID',
    CANCELLED: 'CANCELLED',
} as const;

export const EXPENSE_TYPE = {
    OPERATIONAL: 'OPERATIONAL',
    ADMINISTRATIVE: 'ADMINISTRATIVE',
    MARKETING: 'MARKETING',
    UTILITY: 'UTILITY',
    SALARY: 'SALARY',
    MAINTENANCE: 'MAINTENANCE',
    TRAVEL: 'TRAVEL',
    OTHER: 'OTHER',
} as const;

export const RECURRING_FREQUENCY = {
    DAILY: 'DAILY',
    WEEKLY: 'WEEKLY',
    BI_WEEKLY: 'BI_WEEKLY',
    MONTHLY: 'MONTHLY',
    QUARTERLY: 'QUARTERLY',
    HALF_YEARLY: 'HALF_YEARLY',
    YEARLY: 'YEARLY',
} as const;

// Report related enums
export const REPORT_TYPE = {
    SALES_SUMMARY: 'SALES_SUMMARY',
    SALES_DETAILED: 'SALES_DETAILED',
    SALES_BY_PRODUCT: 'SALES_BY_PRODUCT',
    SALES_BY_CATEGORY: 'SALES_BY_CATEGORY',
    SALES_BY_CUSTOMER: 'SALES_BY_CUSTOMER',
    SALES_BY_USER: 'SALES_BY_USER',
    TOP_PRODUCTS: 'TOP_PRODUCTS',
    TOP_CUSTOMERS: 'TOP_CUSTOMERS',
    INVENTORY_SUMMARY: 'INVENTORY_SUMMARY',
    INVENTORY_DETAILED: 'INVENTORY_DETAILED',
    LOW_STOCK_REPORT: 'LOW_STOCK_REPORT',
    STOCK_MOVEMENT: 'STOCK_MOVEMENT',
    INVENTORY_VALUATION: 'INVENTORY_VALUATION',
    REORDER_REPORT: 'REORDER_REPORT',
    PURCHASE_SUMMARY: 'PURCHASE_SUMMARY',
    PURCHASE_DETAILED: 'PURCHASE_DETAILED',
    PURCHASE_BY_SUPPLIER: 'PURCHASE_BY_SUPPLIER',
    PURCHASE_BY_PRODUCT: 'PURCHASE_BY_PRODUCT',
    SUPPLIER_PERFORMANCE: 'SUPPLIER_PERFORMANCE',
    PROFIT_LOSS: 'PROFIT_LOSS',
    EXPENSE_SUMMARY: 'EXPENSE_SUMMARY',
    EXPENSE_DETAILED: 'EXPENSE_DETAILED',
    EXPENSE_BY_CATEGORY: 'EXPENSE_BY_CATEGORY',
    REVENUE_REPORT: 'REVENUE_REPORT',
    TAX_REPORT: 'TAX_REPORT',
    CUSTOMER_DUES: 'CUSTOMER_DUES',
    CUSTOMER_PAYMENTS: 'CUSTOMER_PAYMENTS',
    CUSTOMER_LIFETIME_VALUE: 'CUSTOMER_LIFETIME_VALUE',
    DISTRIBUTOR_SALES: 'DISTRIBUTOR_SALES',
    DISTRIBUTOR_PERFORMANCE: 'DISTRIBUTOR_PERFORMANCE',
    DISTRIBUTOR_COMMISSION: 'DISTRIBUTOR_COMMISSION',
    USER_ACTIVITY: 'USER_ACTIVITY',
    AUDIT_TRAIL: 'AUDIT_TRAIL',
    SYSTEM_LOGS: 'SYSTEM_LOGS',
} as const;

export const REPORT_FORMAT = {
    PDF: 'PDF',
    EXCEL: 'EXCEL',
    CSV: 'CSV',
    HTML: 'HTML',
    JSON: 'JSON',
} as const;

// Notification related enums
export const NOTIFICATION_TYPE = {
    SYSTEM_ALERT: 'SYSTEM_ALERT',
    SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
    SALE_CREATED: 'SALE_CREATED',
    SALE_CONFIRMED: 'SALE_CONFIRMED',
    SALE_CANCELLED: 'SALE_CANCELLED',
    SALE_REFUNDED: 'SALE_REFUNDED',
    INVOICE_GENERATED: 'INVOICE_GENERATED',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
    PURCHASE_ORDER_APPROVED: 'PURCHASE_ORDER_APPROVED',
    PURCHASE_ORDER_RECEIVED: 'PURCHASE_ORDER_RECEIVED',
    PURCHASE_ORDER_CANCELLED: 'PURCHASE_ORDER_CANCELLED',
    SUPPLIER_PAYMENT_MADE: 'SUPPLIER_PAYMENT_MADE',
    LOW_STOCK_ALERT: 'LOW_STOCK_ALERT',
    OUT_OF_STOCK_ALERT: 'OUT_OF_STOCK_ALERT',
    STOCK_TRANSFER: 'STOCK_TRANSFER',
    EXPIRY_ALERT: 'EXPIRY_ALERT',
    CUSTOMER_DUE_REMINDER: 'CUSTOMER_DUE_REMINDER',
    CUSTOMER_PAYMENT_CONFIRMATION: 'CUSTOMER_PAYMENT_CONFIRMATION',
    CUSTOMER_WELCOME: 'CUSTOMER_WELCOME',
    CUSTOMER_BIRTHDAY: 'CUSTOMER_BIRTHDAY',
    DISTRIBUTOR_ORDER_CREATED: 'DISTRIBUTOR_ORDER_CREATED',
    DISTRIBUTOR_ORDER_SHIPPED: 'DISTRIBUTOR_ORDER_SHIPPED',
    DISTRIBUTOR_ORDER_DELIVERED: 'DISTRIBUTOR_ORDER_DELIVERED',
    DISTRIBUTOR_PAYMENT_RECEIVED: 'DISTRIBUTOR_PAYMENT_RECEIVED',
    DUE_CREATED: 'DUE_CREATED',
    DUE_REMINDER: 'DUE_REMINDER',
    DUE_OVERDUE: 'DUE_OVERDUE',
    DUE_PAID: 'DUE_PAID',
    EXPENSE_CREATED: 'EXPENSE_CREATED',
    EXPENSE_APPROVED: 'EXPENSE_APPROVED',
    EXPENSE_REJECTED: 'EXPENSE_REJECTED',
    EXPENSE_PAID: 'EXPENSE_PAID',
    REPORT_GENERATED: 'REPORT_GENERATED',
    REPORT_SCHEDULED: 'REPORT_SCHEDULED',
    REPORT_DELIVERED: 'REPORT_DELIVERED',
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    LOGIN_ALERT: 'LOGIN_ALERT',
    PROMOTIONAL_OFFER: 'PROMOTIONAL_OFFER',
    NEW_PRODUCT_ARRIVAL: 'NEW_PRODUCT_ARRIVAL',
    SEASONAL_GREETINGS: 'SEASONAL_GREETINGS',
} as const;

export const NOTIFICATION_CHANNEL = {
    EMAIL: 'EMAIL',
    SMS: 'SMS',
    PUSH: 'PUSH',
    IN_APP: 'IN_APP',
    WHATSAPP: 'WHATSAPP',
    TELEGRAM: 'TELEGRAM',
    SLACK: 'SLACK',
    WEBHOOK: 'WEBHOOK',
} as const;

export const NOTIFICATION_STATUS = {
    PENDING: 'PENDING',
    SENT: 'SENT',
    DELIVERED: 'DELIVERED',
    READ: 'READ',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    SCHEDULED: 'SCHEDULED',
} as const;

export const NOTIFICATION_PRIORITY = {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    URGENT: 'URGENT',
} as const;

// General enums
export const UNIT_OF_MEASURE = {
    PIECES: 'PCS',
    KILOGRAM: 'KG',
    GRAM: 'G',
    LITER: 'L',
    MILLILITER: 'ML',
    METER: 'M',
    CENTIMETER: 'CM',
    BOX: 'BOX',
    PACK: 'PACK',
    DOZEN: 'DOZ',
    SET: 'SET',
} as const;

export const WEEK_DAYS = {
    MONDAY: 'MONDAY',
    TUESDAY: 'TUESDAY',
    WEDNESDAY: 'WEDNESDAY',
    THURSDAY: 'THURSDAY',
    FRIDAY: 'FRIDAY',
    SATURDAY: 'SATURDAY',
    SUNDAY: 'SUNDAY',
} as const;

export const MONTHS = {
    JANUARY: 'JANUARY',
    FEBRUARY: 'FEBRUARY',
    MARCH: 'MARCH',
    APRIL: 'APRIL',
    MAY: 'MAY',
    JUNE: 'JUNE',
    JULY: 'JULY',
    AUGUST: 'AUGUST',
    SEPTEMBER: 'SEPTEMBER',
    OCTOBER: 'OCTOBER',
    NOVEMBER: 'NOVEMBER',
    DECEMBER: 'DECEMBER',
} as const;

export const TIMEZONES = {
    IST: 'Asia/Kolkata',
    UTC: 'UTC',
    EST: 'America/New_York',
    PST: 'America/Los_Angeles',
    GMT: 'Europe/London',
    CET: 'Europe/Paris',
    JST: 'Asia/Tokyo',
    AEST: 'Australia/Sydney',
} as const;

export type UserStatus = typeof USER_STATUS[keyof typeof USER_STATUS];
export type CustomerType = typeof CUSTOMER_TYPE[keyof typeof CUSTOMER_TYPE];
export type CustomerStatus = typeof CUSTOMER_STATUS[keyof typeof CUSTOMER_STATUS];
export type DueStatus = typeof DUE_STATUS[keyof typeof DUE_STATUS];
export type LoyaltyTier = typeof LOYALTY_TIER[keyof typeof LOYALTY_TIER];
export type LoyaltyTransactionType = typeof LOYALTY_TRANSACTION_TYPE[keyof typeof LOYALTY_TRANSACTION_TYPE];
export type ProductStatus = typeof PRODUCT_STATUS[keyof typeof PRODUCT_STATUS];
export type StockStatus = typeof STOCK_STATUS[keyof typeof STOCK_STATUS];
export type MovementType = typeof MOVEMENT_TYPE[keyof typeof MOVEMENT_TYPE];
export type SaleStatus = typeof SALE_STATUS[keyof typeof SALE_STATUS];
export type PaymentMethod = typeof PAYMENT_METHOD[keyof typeof PAYMENT_METHOD];
export type PaymentStatus = typeof PAYMENT_STATUS[keyof typeof PAYMENT_STATUS];
export type SupplierStatus = typeof SUPPLIER_STATUS[keyof typeof SUPPLIER_STATUS];
export type PurchaseStatus = typeof PURCHASE_STATUS[keyof typeof PURCHASE_STATUS];
export type DistributorStatus = typeof DISTRIBUTOR_STATUS[keyof typeof DISTRIBUTOR_STATUS];
export type DistributorOrderStatus = typeof DISTRIBUTOR_ORDER_STATUS[keyof typeof DISTRIBUTOR_ORDER_STATUS];
export type ExpenseStatus = typeof EXPENSE_STATUS[keyof typeof EXPENSE_STATUS];
export type ExpenseType = typeof EXPENSE_TYPE[keyof typeof EXPENSE_TYPE];
export type RecurringFrequency = typeof RECURRING_FREQUENCY[keyof typeof RECURRING_FREQUENCY];
export type ReportType = typeof REPORT_TYPE[keyof typeof REPORT_TYPE];
export type ReportFormat = typeof REPORT_FORMAT[keyof typeof REPORT_FORMAT];
export type NotificationType = typeof NOTIFICATION_TYPE[keyof typeof NOTIFICATION_TYPE];
export type NotificationChannel = typeof NOTIFICATION_CHANNEL[keyof typeof NOTIFICATION_CHANNEL];
export type NotificationStatus = typeof NOTIFICATION_STATUS[keyof typeof NOTIFICATION_STATUS];
export type NotificationPriority = typeof NOTIFICATION_PRIORITY[keyof typeof NOTIFICATION_PRIORITY];
export type UnitOfMeasure = typeof UNIT_OF_MEASURE[keyof typeof UNIT_OF_MEASURE];
export type WeekDay = typeof WEEK_DAYS[keyof typeof WEEK_DAYS];
export type Month = typeof MONTHS[keyof typeof MONTHS];
export type Timezone = typeof TIMEZONES[keyof typeof TIMEZONES];