export const LANGUAGES = {
    en: {
        code: 'en',
        name: 'English',
        nativeName: 'English',
        direction: 'ltr',
        flag: '🇬🇧',
        dateFormat: 'MM/DD/YYYY',
        timeFormat: 'hh:mm A',
        firstDayOfWeek: 0, // Sunday
    },
    hi: {
        code: 'hi',
        name: 'Hindi',
        nativeName: 'हिन्दी',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1, // Monday
    },
    ta: {
        code: 'ta',
        name: 'Tamil',
        nativeName: 'தமிழ்',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    te: {
        code: 'te',
        name: 'Telugu',
        nativeName: 'తెలుగు',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    kn: {
        code: 'kn',
        name: 'Kannada',
        nativeName: 'ಕನ್ನಡ',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    ml: {
        code: 'ml',
        name: 'Malayalam',
        nativeName: 'മലയാളം',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    bn: {
        code: 'bn',
        name: 'Bengali',
        nativeName: 'বাংলা',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    gu: {
        code: 'gu',
        name: 'Gujarati',
        nativeName: 'ગુજરાતી',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    mr: {
        code: 'mr',
        name: 'Marathi',
        nativeName: 'मराठी',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    pa: {
        code: 'pa',
        name: 'Punjabi',
        nativeName: 'ਪੰਜਾਬੀ',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    or: {
        code: 'or',
        name: 'Odia',
        nativeName: 'ଓଡ଼ିଆ',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    as: {
        code: 'as',
        name: 'Assamese',
        nativeName: 'অসমীয়া',
        direction: 'ltr',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    ur: {
        code: 'ur',
        name: 'Urdu',
        nativeName: 'اردو',
        direction: 'rtl',
        flag: '🇮🇳',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    es: {
        code: 'es',
        name: 'Spanish',
        nativeName: 'Español',
        direction: 'ltr',
        flag: '🇪🇸',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    fr: {
        code: 'fr',
        name: 'French',
        nativeName: 'Français',
        direction: 'ltr',
        flag: '🇫🇷',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    de: {
        code: 'de',
        name: 'German',
        nativeName: 'Deutsch',
        direction: 'ltr',
        flag: '🇩🇪',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    it: {
        code: 'it',
        name: 'Italian',
        nativeName: 'Italiano',
        direction: 'ltr',
        flag: '🇮🇹',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    pt: {
        code: 'pt',
        name: 'Portuguese',
        nativeName: 'Português',
        direction: 'ltr',
        flag: '🇵🇹',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    ru: {
        code: 'ru',
        name: 'Russian',
        nativeName: 'Русский',
        direction: 'ltr',
        flag: '🇷🇺',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    ja: {
        code: 'ja',
        name: 'Japanese',
        nativeName: '日本語',
        direction: 'ltr',
        flag: '🇯🇵',
        dateFormat: 'YYYY/MM/DD',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 0,
    },
    ko: {
        code: 'ko',
        name: 'Korean',
        nativeName: '한국어',
        direction: 'ltr',
        flag: '🇰🇷',
        dateFormat: 'YYYY/MM/DD',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 0,
    },
    zh: {
        code: 'zh',
        name: 'Chinese',
        nativeName: '中文',
        direction: 'ltr',
        flag: '🇨🇳',
        dateFormat: 'YYYY/MM/DD',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 1,
    },
    ar: {
        code: 'ar',
        name: 'Arabic',
        nativeName: 'العربية',
        direction: 'rtl',
        flag: '🇸🇦',
        dateFormat: 'DD/MM/YYYY',
        timeFormat: 'HH:mm',
        firstDayOfWeek: 6, // Saturday
    },
} as const;

export const DEFAULT_LANGUAGE = LANGUAGES.en;

export const LANGUAGE_LIST = Object.values(LANGUAGES).map(l => ({
    label: `${l.flag} ${l.nativeName}`,
    value: l.code,
    name: l.name,
}));

export const SUPPORTED_LANGUAGES = Object.keys(LANGUAGES) as Array<keyof typeof LANGUAGES>;

export type LanguageCode = keyof typeof LANGUAGES;
export type Language = typeof LANGUAGES[LanguageCode];